environment: production
address: 0.0.0.0
user: hyperion
group: wheel
port: 3000
chdir: /home/hyperion/public_html/epubcakes/current
pid: tmp/thin.pid
rackup: config.ru
log: log/thin.log
max_conns: 1024
timeout: 65
max_persistent_conns: 512
daemonize: true