environment: production
chdir: /home/hyperion/public_html/empaque_pulento
address: 50.57.70.42
user: www-data
group: www-data
port: 80
pid: /home/hyperion/public_html/empaque_pulento/current/tmp/thin.pid
rackup: /home/hyperion/public_html/empaque_pulento/current/config.ru
log: /home/hyperion/public_html/empaque_pulento/current/log/thin.log
max_conns: 1024
timeout: 65
max_persistent_conns: 512
daemonize: true