environment: production
address: 127.0.0.1
user: hyperion
group: wheel
port: 3000
servers: 3
chdir: /home/hyperion/public_html/empaque_pulento/current
pid: tmp/thin.pid
rackup: config.ru
log: log/thin.log
max_conns: 1024
timeout: 65
max_persistent_conns: 512
daemonize: true